### PR TITLE
Make the agent socket configurable

### PR DESCRIPTION
**Pull request by kfox1111**
This patch makes the agent socket configurable.

### CODE REVIEW

**Review by marcofranssen — COMMENTED** [review]
Subcharts can reuse the helpers from the rootChart. With this change we either have a unused root helper that can be removed or we should see if we can reuse that one to have less duplication.

**Comment by faisal-memon** [comment]
Why does this need to be configurable?

**Comment by kfox1111** [comment]
> Subcharts can reuse the helpers from the rootChart. With this change we either have a unused root helper that can be removed or we should see if we can reuse that one to have less duplication.

I just removed the unused helper. Good catch.

**Comment by kfox1111** [comment]
> Why does this need to be configurable?

Its a hostpath. Not all distros put their stuff in the same locations.

**Comment by marcofranssen** [comment]
Haven't we changed this recently all to empty dir volumes? For spire server we also didn't make this configurable. Within the container the path doesn't really matter right.

**Comment by kfox1111** [comment]
We did it on the server because it is only used within the pod.

The agent is different. It has to export it out to the host, so that the csi-driver can import it, and reexport it to all the pods using the csi driver.

**Comment by marcofranssen** [comment]
Oh right. So this goed hand in hand with the csi PR

**Review by marcofranssen — APPROVED** [review]

**Pull request merged**
