### PR TITLE
Add namespace to spiffe-oidc-discovery-provider RBAC definitions

### PR DESCRIPTION
**Pull request by drewwells**
…t namespace

### CODE REVIEW

**Review by kfox1111 — APPROVED** [review]
Good catch. Thanks for fixing this. LGTM

**Review by faisal-memon — APPROVED** [review]
Thanks @drewwells

**Comment by faisal-memon** [comment]
Tests arent running, does this need a rebase?

**Review by marcofranssen — APPROVED** [review]
LGTM :rocket: rerunning the failed test now succeeded.

**Comment by drewwells** [comment]
can i get a merge?

**Comment by kfox1111** [comment]
Its set to automerge, but something is wrong with the tests. @faisal-memon, looks like example-test (v1.27.2, examples/production)  is expected, but the test here is  test (v1.25.9, production-example). Looks like that has something to do with the test refactoring pr?  Is that something you can fix? I don't have permissions to fix that.

**Pull request merged**
