### PR TITLE
Make webhook fail policy configurable

### PR DESCRIPTION
**Pull request by kfox1111**
This patch makes the webhook fail policy configurable.

### CODE REVIEW

**Comment by faisal-memon** [comment]
Im a little hesitant on this one. Its kind of dangerous to have a crd with no protection. To resolve https://github.com/spiffe/helm-charts/issues/72 we can use the pre-upgrade hook to change it to ignore and minimize the window where the webhook is disabled.

**Comment by kfox1111** [comment]
The hooks are clever, but can have unintended side effects.

helm hooks can cause pain with ci/cd systems. I try to avoid them. For example, some will just run:
helm upgrade --install -n spire spire charts/spire -f site-values.yaml

anytime anything changes in the config git repo. with the hooks, it will slow the apply down substantially because the 2 hooks always runs whether anything changes or not causing the webhook to switch back and forth between ignore and fail with each run even while nothing else changes.

Gatekeeper, which may be even more security sensitive then this chart, even defaults to ignore and they do support HA webhooks out of the box:
https://github.com/open-policy-agent/gatekeeper/blob/master/charts/gatekeeper/values.yaml#L10
https://github.com/open-policy-agent/gatekeeper/blob/master/charts/gatekeeper/values.yaml#L1

**Comment by faisal-memon** [comment]
Ok with making the fail policy configurable, but lets keep the default as fail. People with more complex use cases can set it to ignore.

**Comment by kfox1111** [comment]
what about leaving it as ignore for now so upgrades work, until we get the ha webhook in place, then change it back to fail?

**Comment by kfox1111** [comment]
Never intended this to be a permanent thing. Just a workaround for now.

**Comment by faisal-memon** [comment]
> what about leaving it as ignore for now so upgrades work, until we get the ha webhook in place, then change it back to fail?

Got it. Im working on the pre-upgrade hook today. Got sidetracked a bit yesterday. That should fix the upgrade issue.

**Comment by kfox1111** [comment]
Probably need a combination of approaches then.  The pre-upgrade hook is probably ok for some folks, but I'll want to turn it off on my cluster and use this pr to set it to ignore to reduce churn.

So, if that webhook were disable possible to disable, I'll modify this pr to be default fail.

**Review by faisal-memon — APPROVED** [review]

**Pull request merged**
