### PR TITLE
Improve Tornjak documentation

### PR DESCRIPTION
**Pull request by mrsabath**
This change is improving the documentation for Tornjak.
It addresses #402 issue

### CODE REVIEW

**Review by kfox1111 — APPROVED** [review]
lgtm

**Comment by kfox1111** [comment]
Seems like the tests are broken upstream....

**Review by faisal-memon — APPROVED** [review]

**Comment by mrsabath** [comment]
But there is already a test here `examples/tornjak/run-tests.sh` 

> > @marcofranssen thinking the tests not running is associated with your test refactor. Know whats going on here?
> 
> I think we need to add example-test to the ignore ci file.

But there is already a test here `examples/tornjak/run-tests.sh`

**Comment by kfox1111** [comment]
> 
> But there is already a test here `examples/tornjak/run-tests.sh`

There is an issue in main, not particular to this pr thats breaking many pr's. Fix is in progress.

**Review by marcofranssen — APPROVED** [review]

**Pull request merged**
