### PR TITLE
Fix chainguard image references as per issue 442

### PR DESCRIPTION
**Pull request by kfox1111**
fixes: https://github.com/spiffe/helm-charts/issues/442

### CODE REVIEW

**Review by faisal-memon — APPROVED** [review]
Thanks @kfox1111 for fixing this quickly.

**Review by marcofranssen — CHANGES_REQUESTED** [review]
We agreed the following. Took from meeting notes.

```
- Immutable image references - Decided to go with Version@shasum except where version is not available and then latest@shasum will be used.
```

Both @mrsabath and I raised our concerns on the latest tag which we both have blocked in our clusters. E.g. we have kyverno policies that block latest tags e.g.

Can you please lock the bash image on the `5.2.15@sha256:.....`.

**Comment by kfox1111** [comment]
> We agreed the following. Took from meeting notes.
> 
> ```
> - Immutable image references - Decided to go with Version@shasum except where version is not available and then latest@shasum will be used.
> ```
> 
> Both @mrsabath and I raised our concerns on the latest tag which we both have blocked in our clusters. E.g. we have kyverno policies that block latest tags e.g.
> 
> Can you please lock the bash image on the `5.2.15@sha256:.....`.

Can you please read the issue chainguard created? They have made the decision for us and are forcing the issue. Either you'll need to adapt your policy to allow latest with shas, or we will have to switch away from chainguard entirely.

**Comment by marcofranssen** [comment]
> > We agreed the following. Took from meeting notes.
> 
> > 
> 
> > ```
> 
> > - Immutable image references - Decided to go with Version@shasum except where version is not available and then latest@shasum will be used.
> 
> > ```
> 
> > 
> 
> > Both @mrsabath and I raised our concerns on the latest tag which we both have blocked in our clusters. E.g. we have kyverno policies that block latest tags e.g.
> 
> > 
> 
> > Can you please lock the bash image on the `5.2.15@sha256:.....`.
> 
> 
> 
> Can you please read the issue chainguard created? They have made the decision for us and are forcing the issue. Either you'll need to adapt your policy to allow latest with shas, or we will have to switch away from chainguard entirely.

Do you have a link to the issue?

**Comment by marcofranssen** [comment]
Oh 🤦  found it.

**Pull request merged**
