### PR TITLE
Make kubelet path configurable

### PR DESCRIPTION
**Pull request by kfox1111**
Some distro's do not keep their kubelet path at /var/lib/kubelet

fixes: https://github.com/spiffe/helm-charts/issues/109

### CODE REVIEW

**Review by faisal-memon — APPROVED** [review]

**Comment by faisal-memon** [comment]
Does this need to be configurable anywhere else?

**Comment by kfox1111** [comment]
I grepped for /var/lib/kubelet. only cases I could find.

**Comment by faisal-memon** [comment]
> I grepped for /var/lib/kubelet. only cases I could find.

Thanks for checking.

**Review by marcofranssen — APPROVED** [review]
LGTM 🚀

**Pull request merged**
