### PR TITLE
Fix the generated pr so that it runs jobs too

### PR DESCRIPTION
**Pull request by kfox1111**

### CODE REVIEW

**Review by edwbuck — COMMENTED** [review]
Seems reasonable.  Is there any exception for documentation files that are in the test directory (aka *.md or *.adoc)?

**Comment by kfox1111** [comment]
> Seems reasonable. Is there any exception for documentation files that are in the test directory (aka *.md or *.adoc)?

There aren't any documents there at the moment. We can add exceptions if we ever do?

**Comment by edwbuck** [comment]
> > Seems reasonable. Is there any exception for documentation files that are in the test directory (aka *.md or *.adoc)?

> There aren't any documents there at the moment. We can add exceptions if we ever do?

Good enough for me then, accpeting

**Review by edwbuck — APPROVED** [review]

**Comment by faisal-memon** [comment]
How will this resolve the tests not running on https://github.com/spiffe/helm-charts/pull/301? That is a .json file which is already included.

**Comment by kfox1111** [comment]
I'm thinking .github/tests/**/*.json isn't matching .github/tests/*.json? Maybe I'm missing something

**Comment by faisal-memon** [comment]
> I'm thinking `.github/tests/**/*.json` isn't matching `.github/tests/*.json`? Maybe I'm missing something

It should match. I think we are missing something. 

```
➜  .github git:(main) pwd
/Users/fmemon/github.com/spiffe/helm-charts/.github
➜  .github git:(main) ls tests/**/*.json
tests/charts.json
```

**Comment by faisal-memon** [comment]
Another thing to consider is if it doesnt match a path it should have fallen to the paths-ignore path and skipped the tests

**Comment by faisal-memon** [comment]
Is this possibly the reason? https://stackoverflow.com/questions/73079924/github-workflows-not-triggered-by-automatically-created-prs

**Comment by kfox1111** [comment]
> Is this possibly the reason? https://stackoverflow.com/questions/73079924/github-workflows-not-triggered-by-automatically-created-prs

Hmm... yeah. That does sound like it could be the real issue. Will update the pr here to try it.

**Review by marcofranssen — APPROVED** [review]

**Pull request merged**
