### PR TITLE
Bump k8s versions to latest patches

### PR DESCRIPTION
**Pull request by marcofranssen**
@faisal-memon we will need to update the required checks in branch protection to use the new version

### CODE REVIEW

**Review by kfox1111 — APPROVED** [review]
LGTM

**Comment by kfox1111** [comment]
though the tests are broken somehow....

**Comment by kfox1111** [comment]
Probably needs updating here too: https://github.com/spiffe/helm-charts/blob/main/.github/workflows/helm-chart-ci-ignore.yaml

**Comment by faisal-memon** [comment]
@marcofranssen Updated branch protection rules

**Review by faisal-memon — APPROVED** [review]

**Pull request merged**
