### PR TITLE
Align the bash image version with other instances for spire-agent

### PR DESCRIPTION
**Pull request by marcofranssen**
Signed-off-by: Marco Franssen <marco.franssen@gmail.com>

### CODE REVIEW

**Review by kfox1111 — APPROVED** [review]
LGTM

**Review by kfox1111 — CHANGES_REQUESTED** [review]
Actually, I think we need more conversation on this. Refound an issue when reviewing the comments you made on the image updater pr.

Its using the bash version here, 5.2.15. if there is a cve in the same version, it shows up with -r2 and the 5.2.15 tag gets overwritten.
```
$ crane ls cgr.dev/chainguard/bash | grep -v sha256 | grep -v latest
5
5.2
5.2.15
5.2.15-r2
```

So, 5.2.15 is a mutable image, not an immutable one. I'd much rather use immutable images that we test against so they don't float on us and have issues with mirroring/inconsistency on users clusters.

**Review by faisal-memon — APPROVED** [review]

**Comment by marcofranssen** [comment]
> Actually, I think we need more conversation on this. Refound an issue when reviewing the comments you made on the image updater pr.
> 
> Its using the bash version here, 5.2.15. if there is a cve in the same version, it shows up with -r2 and the 5.2.15 tag gets overwritten.
> 
> ```
> $ crane ls cgr.dev/chainguard/bash | grep -v sha256 | grep -v latest
> 5
> 5.2
> 5.2.15
> 5.2.15-r2
> ```
> 
> So, 5.2.15 is a mutable image, not an immutable one. I'd much rather use immutable images that we test against so they don't float on us and have issues with mirroring/inconsistency on users clusters.
> 
> waitForIt image doesn't even have a versioned tag either.

To get a release out it is important that we align the version with the version we use in the remainder of the chart for the last few releases already. We can the discussion in an issue and decide based on that if we want to change anything in a next release. Consistency is key to have explainable behavior in the chart.

**Review by kfox1111 — APPROVED** [review]
We can continue to have this conversation elsewhere.

**Pull request merged**
