### PR TITLE
Add tmp mount so that server can run locked down

### PR DESCRIPTION
**Pull request by kfox1111**
This pr adds a tmp mount to the spire server pod so that it can run with read only root.

### CODE REVIEW

**Comment by faisal-memon** [comment]
The `spire-server-socket` is under `/tmp` and mounted `emptyDir`. Is there something else with `/tmp` thats shared between server and controller manager?

**Comment by kfox1111** [comment]
controller manager writes temporary files directly under /tmp. it doesn't work when the container is marked readonly.

**Comment by faisal-memon** [comment]
Thanks for the explanation. Do we need both mounts or can we consolidate to just the `/tmp` one?

**Comment by kfox1111** [comment]
None of the files controller-manager needs to write out temporarily need to be shared with the other container. So for security reasons, its best to keep them separate.

**Pull request merged**
