### PR TITLE
Remove persistence.enabled flag

### PR DESCRIPTION
**Pull request by faisal-memon**
Its not safe to disable persistence with the helm chart right now. Remove this option for now, revisit later.

### CODE REVIEW

**Comment by kfox1111** [comment]
It is safe to disable persistence in very particular circumstances. Basically just for testing. Instead of removing it, would updating the documentation on the enabled flag to explicitly state, "this should only be disabled for testing purposes" be enough? The feature has been in tree for months.

**Review by marcofranssen — APPROVED** [review]
LGTM 🚀

**Comment by edwbuck** [comment]
Let's remove this for now, because one flag to control three things is just wrong.

This slipped through in a prior pull requests.  It was a design mistake.  Flags that are to be manipulated by the end-users should not control intermediate items like PVCs that the end users don't care about because they are an implementation detail.

This PVC holds the following:

- The backing for the sqlite3 database
- The keystore for the server instance
- The backing store Tornjak

We have flags to turn on and off sqlite3, and the backing store for Tornjak.  We can investigate which approach we want to follow in the future, choosing between the same backing store when anything needs stored being activate or one backing store per activated item.

**Comment by edwbuck** [comment]
I can't add myself as a reviewer, consider this the second accepting review.  Please merge

**Pull request merged**
